#ifndef CONSTANTS_GUARD_H
#define CONSTANTS_GUARD_H

#define DEBUG_LEVEL (0)

#define SCREEN_WIDTH (1600)
#define SCREEN_HEIGHT (900)
#define LEFT_WIDTH (600)
#define DIVIDOR_WIDTH (2)
#define GRID_BLOCK_LENGTH (30)
#define GRID_ITEM_LEN (8)
#define GRAVITY_FRAMES (5)
#define TROLLEY_WIDTH (25)
#define TROLLEY_HEIGHT (11)

#define TROLLEY_X (700)
#define TROLLEY_Y (440)
#define BLOCKS_ABOVE_TROLLEY (8)

#endif