#ifndef CONSTANTS_GUARD_H
#define CONSTANTS_GUARD_H

#define DEBUG_LEVEL (0)

#define SCREEN_WIDTH (1600)
#define SCREEN_HEIGHT (900)
#define LEFT_WIDTH (600)
#define DIVIDOR_WIDTH (2)
#define GRID_BLOCK_LENGTH (30)
#define GRID_ITEM_LEN (8)
#define GRAVITY_FRAMES (10)
#define TROLLEY_WIDTH (20)
#define TROLLEY_HEIGHT (16)

#define TROLLEY_X (829)
#define TROLLEY_Y (360)
#define BLOCKS_FROM_LEFT_TO_TROLLEY (7)
#define BLOCKS_FROM_TROLLEY_TO_RIGHT (25)
#define BLOCKS_ABOVE_TROLLEY (12)

#endif