#ifndef CONSTANTS_GUARD_H
#define CONSTANTS_GUARD_H

#define DEBUG_LEVEL (0)

#define SCREEN_WIDTH (1600)
#define SCREEN_HEIGHT (900)
#define LEFT_WIDTH (600)
#define DIVIDOR_WIDTH (2)
#define GRID_BLOCK_LENGTH (30)
#define TROLLEY_WIDTH (20)
#define TROLLEY_HEIGHT (16)

#endif